### ISSUE TITLE
Split `massa-client` code between REPL abstractions (external crate) and our business commands (that relay on `massa-models`)

### ISSUE THREAD

**Issue by AureliaDolo** [massalabs/massa#1952]
To make external contributions easier (the Russian client looks pretty)

**Comment by AureliaDolo** [comment]
@yvan-sraka @adrien-zinger I'm quite not sure on how to do that. Is it possible to fork only a part of a repo ?

**Comment by adrien-zinger** [comment]
There is multiple possibilities, maybe we want to keep the source code here because when we tag the CI builds a release for the client and for the node. A solution, for me, would be to use a submodule with git. But I want to check if the clone command wont be altered.

Maybe the CI can also build another repo on tagging. It would be better.

**Comment by yvan-sraka** [comment]
I vote for this! We could just have an external repo and use `cargo install` to make it available to CI :)

**Comment by damip** [comment]
sounds good but implies also splitting away "massa-models" which is a dependency of the client. I'm afraid we are heading into too much complexity with this. Marking it for refactoring discussion tho

**Comment by AureliaDolo** [comment]
@AurelienFT @yvan-sraka was this done ?

**Comment by AurelienFT** [comment]
> @AurelienFT @yvan-sraka was this done ?

The PR is still open so I don't think

**Comment by damip** [comment]
This was done in massa-sdk I think. Closing ?
