### ISSUE TITLE
Remove static log limitation

### ISSUE THREAD

**Issue by damip** [massalabs/massa#2111]
In https://github.com/massalabs/massa/pull/2112

All cargo.toml in all massa crates have been set with 

```
tracing = {version = "0.1", features = ["max_level_debug", "release_max_level_debug"] }
```

to reduce a newly-appeared massive JSON serialization overhead caused by traces being computed even when not shown.

This limits the flexibility of changing log levels, and it wasn't a problem before

**Comment by yvan-sraka** [comment]
Have you benchmarked these? could we perform a measured comparison before rollback to `println`? which is for what I know a terrible way of logging things, and that worst in `async` runtime where it behaves like a synchronous lock (because the `write` syscall require an OS round trip) so that's indeed why `tokio` provide a logging utility library :)

**Comment by damip** [comment]
@sebastien-forestier do you still have the perf logs from that benchmark you did that found the performance regression due to serde_json and base58check serializations ? Note that the mentionned static log limitation effectively corrected the problem.

Before the changes that caused the regression, we were using the `stderrlog` crate. I don't think there were any `println!` in the code but I guess both behave similarly.

**Comment by yvan-sraka** [comment]
Maybe the solution would be to solve https://github.com/massalabs/massa/issues/1316 first!

**Comment by damip** [comment]
> Maybe the solution would be to solve #1316 first!

it's solved
