### ISSUE TITLE
Document dummy network generation (free coins)

### ISSUE THREAD

**Issue by qdrn** [massalabs/massa#2187]
### Discussed in https://github.com/massalabs/massa/discussions/1943

Can you add this to the wiki ?

**Comment by Noxhaa** [comment]
@qdrn Ok, I'm thinking of squeezing it in the FAQ for now, and later I will do a dedicated page for community builders when there will be more material.

@AureliaDolo, can you please confirm that your post in #1943 is up to date for episode 6. i.e:
- `initial_rolls.json` and `Initial_ledger.json` still in `massa-node/base_config`
- `staking_keys.json` to add in `massa-node/config`
and more(?)

(I checked with the repo, it seems coherent but just making sure)

**Comment by Noxhaa** [comment]
On another note, issue #1943 made me realize that a wrong "noxha" has been pinged with the move from gitlab to github. Nothing to do about it?

**Comment by AureliaDolo** [comment]
@Noxhaa 
> * edit massa-node/base_config/config.toml genesis timestamp line with a time in millis a few minutes in the future
> * remove end timestamp line from massa-node/base_config/config.toml
> * cargo run in massa-node folder

This part is wrong now, it must be replaced with `cargo run --features test` in the massa_node folder as now with have some conditionnal conpilation witchcraft here https://github.com/massalabs/massa/blob/992573de2b22d7f40d5502e59e946d922d33a57a/massa-consensus/src/settings.rs#L23-L30

The only issue I see is if someone the build and start up time takes more than 3 minutes, they should  `cargo build --release --features test` and then `cargo run --features test`, otherwise they would bootstrap.

**Comment by AureliaDolo** [comment]
> On another note, issue #1943 made me realize that a wrong "noxha" has been pinged with the move from gitlab to github. Nothing to do about it?

The other one seems to not have any activity on github, maybe @yvan-sraka you can make the bot edit its comments to correct the @s  (By the way, it seems like Kesha hasn't been added to the team)

**Comment by Noxhaa** [comment]
@AureliaDolo Ok thanks, I created a page but it's not finished. There is a part of your last comment that I don't understand, we will see tomorrow with a call. thx!

**Comment by Noxhaa** [comment]
https://github.com/massalabs/massa/wiki/Resources-for-community-builders
