### ISSUE TITLE
Network: bug in readbinder?

### ISSUE THREAD

**Issue by gterzian** [massalabs/massa#2278]
In the current implementation, we only [clear](https://github.com/massalabs/massa/blob/3a5e0f6a466d433a3cea4004f0d6cd553a49fed3/massa-network/src/binders.rs#L147) the internal buffer of the binder when we're done successfully receiving a full message. 

In the various error cases, we don't clear it. 

There are various places(for example [here](https://github.com/massalabs/massa/blob/3a5e0f6a466d433a3cea4004f0d6cd553a49fed3/massa-network/src/binders.rs#L97), but the logic is not entirely clear to me. 

Could this be a potential source of corrupted message, in case there is some data left in the buffer from a previous receipt that ended with an error?

It might make sense to allocate a new vector at the start of receiving a new message.

**Comment by damip** [comment]
The readbinder next() function is complicated because it needs to be cancel-safe (see doc comment).

Basically the function can restart from the beginning at any "await" point and we need to avoid losing any data, and we can only use the cancel-safe read() function that returns an arbitrary (>0) number of bytes that were received. We can't use read_all and stuff like that because they are not cancel-safe.

* So we start by checking if we are reading the message length [if self.msg_size.is_none()](https://github.com/massalabs/massa/blob/3a5e0f6a466d433a3cea4004f0d6cd553a49fed3/massa-network/src/binders.rs#L94)  and if we do:
  * we pre-allocate the buffer to fit the encoded message size https://github.com/massalabs/massa/blob/3a5e0f6a466d433a3cea4004f0d6cd553a49fed3/massa-network/src/binders.rs#L97
  * we try to read the full message size field https://github.com/massalabs/massa/blob/3a5e0f6a466d433a3cea4004f0d6cd553a49fed3/massa-network/src/binders.rs#L100-L116  . The `self.cursor` variable indicates how many bytes of the "message size" field we have received so far. We need to keep all states (buffer and cursor) to ensure that if the function restarts at the read's `await`, the state will remain consistent and resume the readout smoothly.
  * once we have the full message size, we deserialize it, we allocate the buffer to match the message length, we set `self.message_size` to indicate that we are now in the process of reading the message contents (and not the size anymore). We also `self.cursor = 0;` so that the cursor now represents how many content bytes have been read.
* we then read the message contents in the same cancel-safe way: https://github.com/massalabs/massa/blob/3a5e0f6a466d433a3cea4004f0d6cd553a49fed3/massa-network/src/binders.rs#L126-L143  
* then we deserialize the message https://github.com/massalabs/massa/blob/3a5e0f6a466d433a3cea4004f0d6cd553a49fed3/massa-network/src/binders.rs#L144
* now the message readout is over, we need to reset the state to start reading the next message's size field again at the next run: https://github.com/massalabs/massa/blob/3a5e0f6a466d433a3cea4004f0d6cd553a49fed3/massa-network/src/binders.rs#L145-L146
* we also clear the buffer to not leave dangling data around (note that clear() doesn't deallocate)
* finally we update sequence numbers and return the deserialized message https://github.com/massalabs/massa/blob/3a5e0f6a466d433a3cea4004f0d6cd553a49fed3/massa-network/src/binders.rs#L149-L151

**Comment by damip** [comment]
@gterzian ping

**Comment by gterzian** [comment]
Thanks, let's close this then.
