### ISSUE TITLE
Transfer coins between sequential and parallel ledgers

### ISSUE THREAD

**Issue by jwmdev** [massalabs/massa#2748]
Massa account supports sequential and parallel coins, which is great. There is a need to support transfer of coins between sequential and parallel ledgers within the same account or different accounts to support some use cases.

The `send_operation` api is proposed to be improved to support transfer of coins between parallel and sequential. The part of the send_operation shown below could be modified from:

```
.....
.....

"Transaction": {
            "amount": String, // represent an Amount in coins
            "recipient_address": String
        }
.....
.....
```
to this
```
....
....

"Transaction": {
            "amount": String, // represent an Amount in coins
            "sender_ledger_type": Number, // 0 = sequential, 1 = parallel (this parameter is optional, default is 0 = sequential)
            "recipient_address": String, 
            "recipient_ledger_type":Number  //  0 = sequential, 1 = parallel (this is parameter is optional, default is 0 = sequential)
        }
....
....
```
If the sender address is the same as the recipient address,  sender_ledger_type and recipient_ledger_type optional parameters must be provided and must not have the same value to enable coin transfer between sequential and parallel ledgers of the same account.

**Comment by damip** [comment]
That's an important thing to deploy indeed ! 
Let's specify the details all together

**Comment by damip** [comment]
## Constraints

* sequential coins can only be spend from operations, and only in their own thread
* fees must be paid only with sequential coins
* protocol staking must remain separate from the smart contract world

## CallSC, ExecuteSC, Transactions

* the "coins" parameter (or amount transferred in the case of transactions) should be split into:
  * "source_parallel_coins" indicating how many parallel coins from the sender need to be spent
  * "source_sequential_coins" indicating how many sequential coins from the sender need to be spent
  * "target_parallel_coins" indicating how many parallel coins need to be credited to the target
  * there is no "target_sequential_coins" because it can be computed as `target_sequential_coins = source_parallel_coins + source_sequential_coins - target_parallel_coins`
* inside the called smart contracts, the "coins" contextual info should be split into "parallel_coins" and "sequential_coins" to indicate the amount of each that was credited at the execution/call

## Inside smart contracts

* coin transfers can only spend the parallel balance, but they should allow choosing how much to credit 
* the "coins" parameter of the async messages, coin transfers and calls should be split into "parallel_coins" and "sequential_coins"
* inside the called smart contracts, the "coins" contextual info should be split into "parallel_coins" and "sequential_coins" to indicate the amount of each that was credited at the execution/call

**Comment by damip** [comment]
@jwmdev Here is an RFC: https://github.com/massalabs/massa/discussions/2791

**Comment by jwmdev** [comment]
@damip Thanks for creating the RFC and giving this issue a milestone of [TEST.14.0](https://github.com/massalabs/massa/milestone/24), I am excite  and looking forward to test this feature.

I have provide my comments in the RFC [#2791](https://github.com/massalabs/massa/discussions/2791)

**Comment by AurelienFT** [comment]
Balances has been unified.

**Comment by jwmdev** [comment]
@AurelienFT and @damip 
Thanks very much... this is one of the features I have been waiting... thanks for the hard work.
