### ISSUE TITLE
Improve pruning of shared storage(use ref counters)

### ISSUE THREAD

**Issue by AurelienFT** [massalabs/massa#2750]
## Context

When the operation pool is full we remove the least interested from the `ops` vector (https://github.com/massalabs/massa/blob/main/massa-pool/src/operation_pool.rs#L201) but we don't remove it from the shared storage.
This causes a major memory leak that makes the nodes crash often.

## Problem

If a operation is in a block, we don't want to delete it from shared storage even if it overflows out of the pool !

## Solution

Have a reference counter on the operation stored to know if it's still used in block and/or operation pool

(cc @gterzian @damip  )

**Comment by gterzian** [comment]
Here is the permalink(for a specific commit) to the code(press `y` on the page to have it) referenced above: https://github.com/massalabs/massa/blob/6b2836ae372465bdeee8697f7026e7ea61891040/massa-pool/src/operation_pool.rs#L201

> If a operation is in a block

In what kind of state would the block be? I assume you mean "a block still used by `graph`"?

**Comment by gterzian** [comment]
Reopening this one for https://github.com/massalabs/massa/pull/2753/files#r914511853

**Comment by gterzian** [comment]
Note panic occuring in execution thead: 

```
thread '<unnamed>' panicked at 'Missing block in storage.', massa-execution-worker/src/execution.rs:639:25
```

See https://github.com/massalabs/massa/issues/2840

**Comment by gterzian** [comment]
Ok this is what I propose:

On the various "owners" of blocks outside of storage:
- A `WrappedBlock` contains not `OperationId`, but `Arc<RwLock<WrappedOperation>>`
- `ExecutionThread` owns not `BlockId` in it various internal structures, but `Arc<RwLock<WrappedBlock>>`.  Execution should also not own a ref to shared storage anymore, to avoid cyclic references.

In shared storage, we should switch to storing something like:
```rust
enum StoredObject<T> {
    Live(Arc<RwLock<T>>),
    Pruned(Weak<RwLock<T>>)
}
```  

When either pool, or graph, prunes an object, it doesn't delete it but set its to `StoredObject::Pruned(..)`. In addition after each prune, or otherwise periodically, we should run through all of storage and remove any object where `StoredObject::Pruned(object) => object.upgrade.is_none()`.

Please let me know what you think @massalabs/core-team @damip

**Comment by gterzian** [comment]
> or otherwise periodically

I propose we add a worker thread which would be woken periodically, and/or perhaps up each time an object is "removed" from the storage, and the worker would run through storage and actual remove entries that have no references to them anymore. 

Could run through storage using a read lock, then do a smaller run with a write lock for the actual removal, and other such optimizations to prevent a "pause the world" kind of GC pause(where the write locks prevents any other threads from using shared storage).

**Comment by damip** [comment]
Hello !
I thought your proposal @gterzian and here are my remarks:

* operations of (older) final blocks can be forgotten but the block should be kept, so WrappedBlock should not contain `Arc`s towards operation IDs. However, Consensus should take care of telling Storage when a set of operations is not needed by Consensus anymore (eg. when the blocks containing it are all final and old enough)
* we need to have performance in mind. Atomics and mutexes are performance-heavy, and we have 10000 operations per second, so we should use them sparingly and batch as much as possible.
* I agree that a GC could be an option, but I think we could do better and simpler

I made a proposal here: https://github.com/massalabs/massa/pull/2851
