### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by damip** [massalabs/massa#2965]
Aurelien's test: after 1h at 2500txps and 2 nodes, we reach 12.3GB of RAM usage.

TODO:
* have a thread print storage.index.block_owners.len(), storage.index.operation_owners.len(), storage.index.endorsement_owners.len() every second
* in massa_async_pool, print AsyncPool.messages.len()
* in op and endorsement pools, print the pool size
* in block_graph, print block_statuses.len() after every block_db_changed
* in protocol:
  * print block_wishlist.len()
  * print checked_endorsements.len()
  * print checked_operations.len()
  * print checked_headers.len()
  * print asked_operations.len()
  * print op_batch_buffer.len()
  * print sum_i(active_nodes[i].known_blocks.len())
    * same for node_info.asked_blocks
    * same for node_info.known_operations
    * same for node_info.known_operations_queue
    * same for node_info.known_endorsements
    * same for node_info.known_endorsements_queue

**Comment by AurelienFT** [comment]
On node that receive operations : 
```
DEBUG: Size of checked_operations: 12213532
```

On node that don't receive : 
```
DEBUG: Size of checked_operations: 72042
```

I think it's because `note_operations_from_node` doesn't receive operations but so the vector isn't clear. That's a problem.
But the difference between the two node is only 600MB so this is a problem but not the main I think. The node that have the less have 6.7 GB after 1h.

**Comment by AurelienFT** [comment]
In storage on both node we have 7 000 000 after 1 hour. With 2k5/s I don't think we should keep that much

**Comment by AurelienFT** [comment]
In storage blocks stay around 800 on both nodes. If we make calculation 800 * 1250 = 1 000 000 + 493949 from pool = 1 500 000 but we have 7 000 000 and it keep going up so I think there is a problem.

**Comment by AurelienFT** [comment]
When ops are pruned from the pool they are not removed from storage.

**Comment by AurelienFT** [comment]
I have seen that the node is stable for some times and then bump memory of 4GB.

**Comment by AurelienFT** [comment]
I have spotted why the operations are not clear from storage. They are never drop from operations pool because of : 
```rust 
                    if !added.remove(&op_info.id) {
                        removed.insert(op_info.id);
                    }
```
at L 173 of operation_pool.rs. And as all the tx have the same quality with the spammer they are removed from the buffers but not storage.
I have removed the if.
I think this has been implemented to avoid cleaning operations that we just inserted. If we want to re-insert this rule we can discuss about it.

**Comment by AurelienFT** [comment]
Current PR with debug print and fixes : https://github.com/massalabs/massa/pull/2966

**Comment by AurelienFT** [comment]
This fix some errors but doesn't fix the memory explode of 1/2 GB.

**Comment by AurelienFT** [comment]
Seems to be fixed on the PR. Stay at 2,5GB and stable values that doesn't go more than excepted ones. Pool is still filed as half so goind to 4GB wouldn't be a surprise but shouldn't go more. Let's see tomorrow morning.

**Comment by AurelienFT** [comment]
The operation_pool still goes too high on the PR but less. Only 4GB after 1h
