### ISSUE TITLE
Testnet crash

### ISSUE THREAD

**Issue by AurelienFT** [massalabs/massa#3030]
TBD

**Comment by r1k0** [comment]
logs (not debug sry) since start of 14.3 massad service
[testnet_14.3.txt](https://github.com/massalabs/massa/files/9587287/testnet_14.3.txt)

RAM + CPU started going up unreasonably between 22h40m and 22h45m and network traffic started being unstable too

that matches the moment where in the logs line like these started to appear:

Sep 16 22:46:11 massa massa-node[27174]: #033[2m2022-09-16T20:46:11.958203Z#033[0m #033[33m WARN#033[0m #033[2mmassa_execution_worker::worker#033[0m#033[2m:#033[0m address A12Qtpki1aebNsjRzR6RDTzT6tex8qanEVL6nDX4eM8jijFdUhs2 missed a production opportunity at slot (period: 614, thread: 3) (cycle 4)
Sep 16 22:46:35 massa massa-node[27174]: #033[2m2022-09-16T20:46:35.255363Z#033[0m #033[33m WARN#033[0m #033[2mmassa_protocol_worker::protocol_network#033[0m#033[2m:#033[0m Node P1E8G95wgFJnhmBXuk5AWsC5BcBgfJSskNCaECKzmFQDNM9y4cn sent us an operation list for block id ftrPrWf1gDFRPwKSdudUJ5JZ9w5z49y4tpnCun3rvzLEZZ2SW but we already received it.
Sep 16 22:46:41 massa massa-node[27174]: #033[2m2022-09-16T20:46:41.495687Z#033[0m #033[33m WARN#033[0m #033[2mmassa_protocol_worker::protocol_network#033[0m#033[2m:#033[0m Node P13Ykon8Zo73PTKMruLViMMtE2rEG646JQ4sCcee2DnopmVM3P5 sent us full operations but we don't have the block id x842WJKRxjMr6gtiHuiEGZ1kU7FFPgSEqV4pFBQAsfyk91PQk in our wishlist.
Sep 16 22:46:43 massa massa-node[27174]: #033[2m2022-09-16T20:46:43.243045Z#033[0m #033[33m WARN#033[0m #033[2mmassa_protocol_worker::protocol_network#033[0m#033[2m:#033[0m Node P12ehdqMxVoGm6H4KYTagdm8DsKB77yp5kZy2pztyj3gbru9tG9r sent us an operation list for block id 2fckAaE19JfgoNX8zXD6MkGJR9PQUYZqtrLjDLNiXKNQpt1KHe but we already received it.
Sep 16 22:46:43 massa massa-node[27174]: #033[2m2022-09-16T20:46:43.556310Z#033[0m #033[33m WARN#033[0m #033[2mmassa_protocol_worker::protocol_network#033[0m#033[2m:#033[0m Node P1hdgsVsd4zkNp8cF1rdqqG6JPRQasAmx12QgJaJHBHFU1fRHEH sent us full operations but we don't have the block id 2mzeaAJW6BcX3EuzSMaqaeUXnSwF4EdavwUTHLedUQrtdvYJkf in our wishlist.
Sep 16 22:46:49 massa massa-node[27174]: #033[2m2022-09-16T20:46:49.544953Z#033[0m #033[33m WARN#033[0m #033[2mmassa_protocol_worker::protocol_network#033[0m#033[2m:#033[0m Node P13Ykon8Zo73PTKMruLViMMtE2rEG646JQ4sCcee2DnopmVM3P5 sent us full operations but we don't have the block id 2fckAaE19JfgoNX8zXD6MkGJR9PQUYZqtrLjDLNiXKNQpt1KHe in our wishlist.
Sep 16 22:46:56 massa massa-node[27174]: #033[2m2022-09-16T20:46:56.342987Z#033[0m #033[33m WARN#033[0m #033[2mmassa_protocol_worker::protocol_network#033[0m#033[2m:#033[0m Node P1hdgsVsd4zkNp8cF1rdqqG6JPRQasAmx12QgJaJHBHFU1fRHEH sent us an operation list for block id szAvRmmxFP2WmXmtJLEaaJ93vTPo41QEoh7SLA5TcmboBoRaK but we already received it.
Sep 16 22:47:05 massa massa-node[27174]: #033[2m2022-09-16T20:47:05.029069Z#033[0m #033[32m INFO#033[0m #033[2mmassa_factory_worker::block_factory#033[0m#033[2m:#033[0m block 2esTr3VQg6kv2auN5mSup57F2pkaMt2r3GWmx35jpSjSw8cQdU created at slot (period: 626, thread: 18) by address A12RHPuU7JFS2rxvxL6MnzVoBJAZr7ivFFJuiRPv4mi5wv8z8VYm

![Screenshot 2022-09-16 232120](https://user-images.githubusercontent.com/238676/190769529-9c981a13-a7f0-4a9d-88f8-9207d28c97ac.png)

**Comment by AurelienFT** [comment]
Image on which slot testnet died :

<img width="1440" alt="Screenshot 2022-09-19 at 21 28 48" src="https://user-images.githubusercontent.com/32803821/191101037-d30d8c2f-a8f8-47f6-b4d4-7bb0621a1080.png">
<img width="1440" alt="Screenshot 2022-09-19 at 21 29 01" src="https://user-images.githubusercontent.com/32803821/191101042-f504e028-58ce-4826-84c7-dc952d83fc93.png">
Logs on testnet 3:

<img width="1440" alt="Screenshot 2022-09-19 at 21 36 40" src="https://user-images.githubusercontent.com/32803821/191101045-3a94356e-bc10-41fc-a11d-3a776bab0a37.png">

**Comment by AurelienFT** [comment]
This error doesn't appear in this testnet anymore.
