### ISSUE TITLE
Remove tokio from massa-sdk

### ISSUE THREAD

**Issue by BatiGencho** [massalabs/massa#3066]
For our games to run in a single-threaded wasm env (web3 in the browser), the game engine I am using (macroquad.rs) needs to run in a single-threaded (non-tokio) mode. For this reason, any tokio dependencies from our sdk need to be removed. Can we prepare a special version which does not depend on tokio maybe since the current one does (incl. the underlying json rpc lib which I presume is not tokio-dependent)?

**Comment by BatiGencho** [comment]
@qdrn fyi

**Comment by AurelienFT** [comment]
We have dependencies that use async we will to make a second version totally different. @BatiGencho  I think a better solution if you need to run on a single thread would be to setup tokio in your code so that it runs one thread. Here is a documentation about it : https://docs.rs/tokio/latest/tokio/runtime/index.html#current-thread-scheduler

**Comment by BatiGencho** [comment]
@damip @AurelienFT @qdrn Aurelien's suggestion wont work as the tokio env is getting rejected by the game engine at all. I already tried setting using a single threaded rt, but it fails as it refuses any runtime engine apart from the rust core async/await futures. Therefore, macroquad (which I picked as being simplistic) wont work with our sdk in rust env.
Hence I am suggesting continuing with the bevy engine which supports tokio out of the box and that wont have any issues. The first prototype I did was usign Bevy but relying on js bindings outside of the wasm to interact with massa. Since I have now made a massa-sdk wrapper for the gaming part, I will try to put this back into bevy which should then work. I guess there is no need to do anything to the sdk as of this moment.

**Comment by damip** [comment]
The whole massa-sdk currently depends on async rust because the underlying JSON-RPC lib uses async futures. There is currently no plan to change that within Massa. The successor will be https://github.com/paritytech/jsonrpsee which also uses async/await. That's because async/await is a very good fit for this kind of applications.

However it would for sure be interesting to have another, non-async version somewhere for this kind of purposes.
