### ISSUE TITLE
Error transferring coins SC

### ISSUE THREAD

**Issue by AurelienFT** [massalabs/massa#3093]
From community : 

I want to write a simple sc that sends coins from one address to another. Program works good until the line of "transferCoinsOf" function
the output without "transferCoinsOf":
```
Data: Sender Address: A1RDQQBKriCF7jXr9dDW65JCt346XCjYLd1KXv62nTtiuiy7P17
      Balance of Sender Address:200
Data: Reciever Address: A18eMYGi7jRFQ1WW9WejQ7JFC4fGdHUnFioCoyR5ZnV5w3G2sBZ
      Balance of Reciever Address:0
```
 when I uncomment it:
```
Data: {"massa_execution_error":"Runtime error: runtime error when executing operation kQP1aqDzKBujbDFhovUUi7HuGfc3xg6FzcXhYoeTgswZ6WphD: Runtime error: bytecode execution error: RuntimeError: RuntimeError: Runtime error: spending from address A1RDQQBKriCF7jXr9dDW65JCt346XCjYLd1KXv62nTtiuiy7P17 is not allowed in this context\n    at <unnamed> (<module>[14]:0x1076)\n    at <unnamed> (<module>[7]:0x8fd)"}
```
the code:
```
import { Address, transferCoinsOf, generateEvent, Context, balanceOf } from "@massalabs/massa-sc-std"

export function sendCoin(name: string): void {
    //**********Define addresses
    const baseAccount = Context.caller();
    const target = new Address();
    target._value = name;
    target._isValid = true;
    //**********Define balances
    let coins : u64;
    let coins2 : u64;
    coins = balanceOf(baseAccount.toByteString());
    coins2 = balanceOf(target.toByteString());
    //**********Print informations about addresses
    generateEvent("Sender Address: " + baseAccount.toByteString() + "\n      Balance of Sender Address:" + coins.toString());
    generateEvent("Reciever Address: " + target.toByteString() + "\n      Balance of Reciever Address:" + coins2.toString());
    //**********Transfer coins
    //transferCoinsOf(baseAccount, target, 1);
}
```

**Comment by damip** [comment]
Here is a little explanation and comments about that (expected) behavior:
* `transferCoinsOf` transfers coins from an address on which the top of the stack has write access. In that example, the top of the stack has only write access to the top of the stack itself, as it has not created any addresses in that execution
* `Context.caller()` is defined here: https://github.com/massalabs/massa-as-sdk/blob/2fd325be0f0f2fe115fc94fe0969e95b4ea28b1d/assembly/std/context.ts#L46-L57  and basically takes the element just below the top of the stack. Unless the two topmost stack addrs are the same, this implies that the top of the stack has no write access to the addr returned by caller() and can therefore not spend its coins.

The limited write-access is a security measure preventing the smart contracts you call from doing arbitrary actions on your address like stealing all your coins.

How to solve the problem:
* if you want to send coins from the smart contract hosting the sendCoin function, use `Context.callee()` instead of `Context.caller()`. Or even better, just use  `transferCoins` for which the source is implicitly the top of the stack (see https://github.com/massalabs/massa-as-sdk/blob/2fd325be0f0f2fe115fc94fe0969e95b4ea28b1d/assembly/std/index.ts#L64-L72 )
* if you want to transfer coins from your (caller) address to the smart contract hosting the sendCoin function you are calling, for it to be able to forward them to another address, use the `coins` parameter of  `call` (https://github.com/massalabs/massa-as-sdk/blob/2fd325be0f0f2fe115fc94fe0969e95b4ea28b1d/assembly/std/index.ts#L17-L36) , which will send those coins to the smart contract when called. The smart contract can know how many coins were transferred in the call by using https://github.com/massalabs/massa-as-sdk/blob/2fd325be0f0f2fe115fc94fe0969e95b4ea28b1d/assembly/std/context.ts#L80-L87

How to make things better:
* the `caller()` and `callee()` methods should be better documented because they can be misleading (eg. `caller()` fails on ExecuteSC when there is only 1 stack element)
* write a tutorial on write access rights, security practices, and the way the call stack works

**Comment by gregLibert** [comment]
> the caller() and callee() methods should be better documented because they can be misleading (eg. caller() fails on ExecuteSC when there is only 1 stack element)

From what I understand from the code, `caller()` does not fail, but returns an invalid address because there is no caller from an ExecuteSC. 

@damip, are you expecting another behavior?

**Comment by nirnaeth-arnoediad** [comment]
@damip Thank you for this explanatory answer. I have changed `transferCoinsOf` to `transferCoins` but after that I got an error about "insufficient balance". So I checked my balance again with proper way and yes it is shown 0 but actually I got 1 active roll and more than 200 MAS. Top of the stack is also caller address. Any idea?
Code:
`const stack = Context.addressStack();
 const baseAccount = stack[0];
 let coins : u64;
 coins = balance();
 generateEvent("Sender Address: " + baseAccount.toByteString() + "\n      Balance of sender address before operation: " + coins.toString());`
 Output:
 `✔ command · get_filtered_sc_output_event operation_id=ieGqYbVnubG6CB2EKfib7QaLGJShPDW6X4uoxx9X328h8s6T9
Context: Slot: (period: 48713, thread: 6) at index: 0
On chain execution
Block id: 2rkJeMmGpAV95v7YoZw91AnBFVe3ctKBmwiAjbxdmqvd1HjrM3
Origin operation id: ieGqYbVnubG6CB2EKfib7QaLGJShPDW6X4uoxx9X328h8s6T9
Call stack: A1RDQQBKriCF7jXr9dDW65JCt346XCjYLd1KXv62nTtiuiy7P17,A1TaHkaXEe6YB5AysE3q5brNaoC7W1jQZKQaXjdKTsEkmSLobBv

Data: Sender Address: A1RDQQBKriCF7jXr9dDW65JCt346XCjYLd1KXv62nTtiuiy7P17
      Balance of sender address before operation: 0
`
wallet_info:
`Address: A1RDQQBKriCF7jXr9dDW65JCt346XCjYLd1KXv62nTtiuiy7P17 (thread 6):
        Sequential balance: final=219.74, candidate=219.74
        Parallel balance: final=0.0000002, candidate=0.0000002
        Rolls: active=1, final=1, candidate=1
`

**Comment by AurelienFT** [comment]
@nirnaeth-arnoediad The coins that are used in SC world is sequential ones. You have to fill the parameter call of your ExecuteSC or CallSC operation to transfer coins from your sequential balance to the parallel one and be used in your SC.

This behavior will disappear in TEST.15 because balance will be unified and you will have only one classic balance that work for all the use cases.

**Comment by nirnaeth-arnoediad** [comment]
> @nirnaeth-arnoediad The coins that are used in SC world is sequential ones. You have to fill the parameter call of your ExecuteSC or CallSC operation to transfer coins from your sequential balance to the parallel one and be used in your SC.
> 
> This behavior will disappear in TEST.15 because balance will be unified and you will have only one classic balance that work for all the use cases.

Allright then I will be waiting for next version to test.

**Comment by nirnaeth-arnoediad** [comment]
Hey @AurelienFT . I want to inform you that `balance()` function still shows my balance `zero` but it is not actually.

**Comment by AurelienFT** [comment]
> Hey @AurelienFT . I want to inform you that `balance()` function still shows my balance `zero` but it is not actually.

I just tried on my side and I can get the balance with a SC. Can you send me your SC in private ?

**Comment by nirnaeth-arnoediad** [comment]
main.ts
```
import { createSC, fileToBase64, call } from "@massalabs/massa-sc-std";

export function main(_args: string): void {
    const bytes = fileToBase64("./build/smart-contract.wasm");
    let addr = createSC(bytes);
    call(addr, "sendCoin", "A1fREq7u1BeS8XsXimYuTnR6ahyfw3gmrTz1fqUKwTMvCSs5wuj", 0);
}
```
smart-contract.ts
```
import { Address, transferCoins, generateEvent } from "@massalabs/massa-sc-std";

export function sendCoin(name: string): void {
    const target = new Address();
    target._value = name;
    transferCoins(target, 1);
    generateEvent("Operation successful");
}
```
package.json
```
{
  "name": "send-token",
  "version": "0.1.0",
  "scripts": {
    "build": "massa-sc-scripts build-sc src/smart-contract.ts && massa-sc-scripts build-sc src/main.ts build/main.wasm",
    "clean": "massa-sc-scripts clean"
  },
  "dependencies": {
    "@massalabs/massa-sc-std": "^4.0.2",
    "assemblyscript": "^0.19.20",
    "massa-sc-scripts": "4.0.7",
    "prettier": "^2.7.1"
  }
}
```
execution output
```
Context: Slot: (period: 21593, thread: 15) at index: 290
On chain execution
Block id: 2q7FFGsRAM8He7URiVQioVm7pcedQSvMMjQuhPhA5eEW6cXZcK
Origin operation id: 29ZEPyr4nxheUGLuUSpzPksbL2cyuybZ2xFrA4XpqQEAgYxSWg
Call stack: A1yBuHitvccgdMEcyKY1Xd2zaKNhmXQBCVc5niBW6ETYAZXWZsL,A12wGJRfj1wop31LnsKtX8qRFqFhgeUmwosxoCizgrDZSP4hz772

Data: {"massa_execution_error":"Runtime error: runtime error when executing operation 29ZEPyr4nxheUGLuUSpzPksbL2cyuybZ2xFrA4XpqQEAgYxSWg: Runtime error: bytecode execution error: RuntimeError: RuntimeError: Runtime error: insufficient from_addr balance\n    at <unnamed> (<module>[4]:0x1f5)\n    at <unnamed> (<module>[4]:0x1ea)"}
```
V15.1

**Comment by qdrn** [comment]
The address to which you are sending coin has a zero balance. Since testnet 15, creating an address has a cost (this is to limit the size of the ledger). This cost is `0.01 Massa`. This is the minimum amount that you must send to an address that has a balance of zero Massa. When you write the SCs, the amounts are raw and not in decimal, this correspond to the following string: `10000000`. Also, it is the SC created by `smart-contract.ts` that will send the coin, so you should first send coins to this SC so that is has a non-zero balance.

More details on storage cost here: https://docs.massa.net/en/latest/technical-doc/storage-costs.html

Here is a working example:

main.ts
```ts
import { createSC, fileToBase64, call } from "@massalabs/massa-sc-std";

export function main(_args: string): void {
    const bytes = fileToBase64("./build/smart-contract.wasm");
    let addr = createSC(bytes);
    call(addr, "sendCoin", "A1fREq7u1BeS8XsXimYuTnR6ahyfw3gmrTz1fqUKwTMvCSs5wuj", 10000000);
}
```

smart-contract.ts
```
import { Address, transferCoins, generateEvent } from "@massalabs/massa-sc-std";

export function sendCoin(name: string): void {
    const target = new Address();
    target._value = name;
    transferCoins(target, 10000000);
    generateEvent("Operation successful");
}
```
