### ISSUE TITLE
Massa Client/Bot to use single output/input

### ISSUE THREAD

**Issue by UnNicky** [massalabs/massa#3157]
**Is your feature request related to a problem? Please describe.**
I had an issue after the server change (due to HW failure). Massabot was configured for the previous node ID, stake ID and IP, once I created a new node on the new server, I passed IP to Massabot. Patiently waiting for episode start. Once it's started massabot shown 0 routable samples, despite https://paranormal-brothers.com/massa/ shown Node is routable. The rest appears ok.
The reason behind I suppose was the change of Node ID on the server, while I didn't submit new node_testnet_rewards_program_ownership_proof to discord bot, and discord bot didn't inform (not sure whether it's possible) me after IP change that node ID there is different. Anyhow the issue was solved by submitting new node_testnet_rewards_program_ownership_proof output to bot and node restart.

**Describe the solution you'd like**
My suggestion is to include IP address into node_testnet_rewards_program_ownership_proof output of massa client and use one single line submit to register(change registration) node at massabot

**Describe alternatives you've considered**
Considered checks that new IDs from node_testnet_rewards_program_ownership_proof  during submit to bot differs to what current IP has and vise versa if new IP submitted to the bot, the bot would inform that node ID and/or stake ID currently under monitoring is different. Though these two possible solutions appears trickier then a single line submit with IP inside. 

**Additional context**
![image](https://user-images.githubusercontent.com/113925134/195825892-49f6a5e3-7ea9-4ee4-98d0-38148973533d.png)
![image](https://user-images.githubusercontent.com/113925134/195825935-873648c6-6558-4224-b01d-205dcdeb3d4d.png)
earlier screenshot shows old node ID, thus routable samples was 0, while new IP was accepted by the bot
at 11:40
active_cycles: 16
routability_trials: 16
nb_cycles_episode: 650
produced_blocks: 18
selected_slots: 18
routable_samples: 0
total_maxim_factor: 0.0

at 12:08
active_cycles: 17
routability_trials: 17
nb_cycles_episode: 650
produced_blocks: 18
selected_slots: 18
routable_samples: 1
total_maxim_factor: 0.72

**Comment by AurelienFT** [comment]
Hello,

Thanks for your reporting.

> My suggestion is to include IP address into node_testnet_rewards_program_ownership_proof output of massa client and use one single line submit to register(change registration) node at massabot

We don't want to do that because sometimes people don't want to be routable, for multiple reasons, and they need to be able to participate.

We can't really tell you that the node ID differ from yours easily. I think it's the role of participants to check wherever they give good informations to the bot or now. However, we can add a line in documentation about that. We will do it but it's out of the scope for this issue so I will close it.

In a more general way, we will not put big efforts on the developments of the tools for the testnet as it will end soon and give us less time to work on features for mainnet.
