### ISSUE TITLE
Optim ledger_db get_datastore_keys 

### ISSUE THREAD

**Issue by sydhds** [massalabs/massa#3275]
get_datastore_keys() should return None if addr does not exist but for now it will return an empty BTreeSet.

So the get_keys in speculative_ledger.rs should do first an entry_exists() and then a get_datastore_keys() and it looks suboptimal because the balance (tested for entry_exists) and the datastore keys are consecutive in the ledger, but we fully independently look them up without hints (logarithmic search).

**Comment by Ben-PH** [comment]
What I'm thinking at this point, is to provide an interface that allows you to do a batch-get of the data-base entries using [this method](https://docs.rs/rocksdb/0.19.0/rocksdb/struct.DBCommon.html#method.batched_multi_get_cf).

I'm thinking something like this (except not so jankey. Perhaps with builder pattern, and perhaps encapsulate the types somehow)
```rust
    pub fn batch_get_sub_entries(&self, address: &Address, balance: bool, bytecode: bool, datastore: Option<Vec[u8]>) -> Option<(Option<Vec[u8]>, Option<Vec[u8]>, Option<Vec[u8]>)> 
```

This could allow for a refactor of `entry_exists()` to 

- when need to know if anything exists, just get something, and follow up with a `is_some()` further up the stack
- when used in the context of what this issue is trying to address, can get what's needed, while leaning into the rocks-db optimisations available.

unless there is a way to make assumptions about storage, thus allowing us to get all three in a single get?

**Comment by Ben-PH** [comment]
Continuing this discussion in #3437
