### ISSUE TITLE
Study libp2p in context of our network refactoring

### ISSUE THREAD

**Issue by AurelienFT** [massalabs/massa#3577]
In the context of the [network refactoring](https://github.com/massalabs/massa/discussions/3149) we want to study if libp2p could be a fit for us.

The goal is to have a detailed report on the usage of libp2p in our case of low number of connections but that live for a long time. We need to have justified answers on, at least, the following points : 

- Is it more optimized to use async architecture like the libp2p in our case ? (benchmarks could be great to justify)
- With which solution the code readability/debugging are the best ?
- How the transfer of messages in libp2p works and can we use our serialization system ?
- ...

I don't have much ideas for now maybe something will be discovered while making the searches. If I find more ideas during time I will add them in comment

Here is some answers elements I already find that can help : 
- https://tomaka.medium.com/a-look-back-at-asynchronous-rust-d54d63934a1c
- https://www.youtube.com/watch?v=HqSXFlCwgMY

**Comment by gterzian** [comment]
I will look into it this week.

**Comment by Ben-PH** [comment]
For my tech-test to join mass, I came across libp2p and considered using it, but thought of that a bit like "cheating".

It might be one option to have a go at implimenting the tech-test using libp2p as a way to gather the understandings to put this

**Comment by gterzian** [comment]
Here is an update on my current research, please read it, ask questions, and I could also present something in a call later. 
...

[Libp2p](https://docs.rs/libp2p/latest/libp2p/) is more of a framework than a library; switching to it will require large changes in the code, which can be summarized as the below. 

1. Protocol and Network workers would have to be translated into structs implementing the [NetworkBehaviour](https://docs.rs/libp2p/latest/libp2p/swarm/trait.NetworkBehaviour.html) trait
2. Node worker would have to be translated into a struct the implements the [ConnectionHandler](https://docs.rs/libp2p/latest/libp2p/swarm/trait.ConnectionHandler.html) trait.
3. Binders will have to be translated into a transport, although perhaps the default transports provided by libp2p can be used. 

An example of what the code would end-up looking like can be found in the implementation of the Kademlia protocol: https://github.com/libp2p/rust-libp2p/tree/master/protocols/kad/src

Note that this is not the usual async/await type of code as currently used, rather each struct acts as a kind of Stream with a `poll` method. Also, instead of channels for messaging as now, you have the rely on the event system as provided libp2p. I refer to the documentation and the example above for more details on how it works. 

Doing the serialization in a separate thread, outside of say the connection handlers, would also require some scaffolding and plugging into the event system of libp2p.

Whether libp2p or the current approach is easier to understand and debug is a matter of personal preference. The main difference is whether you structure your own code and use libraries where you need them(like the current use of tcp from tokio), or whether you follow the approach mandated by the framework and rely on the ecosystem(like the default transport for tcp provided by libp2p). The example of (de-)serializing messages on a separate thread(s) shows how the framework can become something you have to work around to do what you want. 

I don’t have a benchmark yet, my guess is that with a small number of connection like in your case, performance should be similar. More generally, you might get some benefit from the tcp stream multiplexing that libp2p does(although there is perhaps some tokio based library that provides the same). 

One thing that seems to be missing from the Rust [implementation](https://libp2p.io/implementations/) of libp2p, is a default way to boostrap. It seems the Kademlia implementation does something internally but I haven’t yet looked into the details. One could first switch `massa-protocol` and `massa-network` over to libp2p, while maintaining `massa-bootstrap` as it is, later switching it over as well.

@massalabs/core-team

**Comment by gterzian** [comment]
> It might be one option to have a go at implimenting the tech-test using libp2p as a way to gather some understandings to put this report together

Yes that could be a good idea. Do you have a link to the work in progress or the issue?

**Comment by AurelienFT** [comment]
Thanks for the first update.

> rather each struct acts as a kind of Stream with a poll.

Is that better in our use case of low connection numbers ? While searching I found that was pretty similar with low amount of connections

> although there is perhaps some tokio based library that provides the same).

I checked MIO is that related or didn't understood ?

The problem of thread creation for special tasks could be rough to us.

Do you think it will take longer to make a simple library from scratch with our architecture or change to use the framework ? Because if it's still that difficult to change to use the framework we shouldn't do it as it will add a lot of code that we don't know and a lot more overhead than having our proper little library that manage our use case.

**Comment by gterzian** [comment]
> Is that better in our use case of low connection numbers ?

 I don't think it matters regarding performance, what I mean is that it's not like the current style of coding using async/await, so it may be confusing at first(the methods are not actually `async`, you need to transition from one state to the next via the `poll` method). 

>

MIO is the event system underlying tokio, so it's not related. I mean something that would do [this](https://docs.libp2p.io/concepts/multiplex/overview/). On second thought I don't think it's relevant, because it seems mostly useful if you are running multiple processes on one machine.  

> The problem of thread creation for special tasks could be rough to us.

I think the event system of libp2p is complicated, I only understood it after reading how that kademlia protocol uses it. The docs alone were not enough. 

In the current setup, the big `select` on many channels and running different tasks may appear complicated, but if you want to find out how a certain event travels through, you can just follow the code. It's explicit. 

Currently, if you want to for example add a thread, or a threadpool, that would serialize messages before they are send on a binder, it's just a matter of adding a channel to one of the existing selects. With libp2p, it would be possible but more complicated, because you would have to route everything through their event system, which would add more layers to the workflow(as an illustration, a [connection handler](https://github.com/libp2p/rust-libp2p/blob/4910160bea49dc6fe890be260e20339952bde35f/protocols/kad/src/handler.rs#L47), which is the thing that owns the tcp stream to a node, couldn't just send a message to some "message serializer" and wait on the serialized message from within it's own select loop, instead the "message serializer" would have to route the serialized message back through the event system, for it to be eventually [delivered](https://github.com/libp2p/rust-libp2p/blob/4910160bea49dc6fe890be260e20339952bde35f/protocols/kad/src/handler.rs#L629) to the connection handler. A more indirect workflow). 

> Do you think it will take longer to make a simple library from scratch with our architecture or change to use the framework ? Because if it's still that difficult to change to use the framework we shouldn't do it as it will add a lot of code that we don't know and a lot more overhead than having our proper little library that manage our use case.

I think it would be simpler to keep what you have and change it gradually. If you remove most of the async like done in https://github.com/massalabs/massa/pull/3272, you can easily experiment with moving message serialization to a thread(-pool), and you can also experiment with blocking networking to see if it improves performance. 

I think they are plenty of libraries in the Rust ecosystem that you can mix and match based on your needs, with no need to tie yourself to one particular way of doing things, like I think libp2p mandates.
