### ISSUE TITLE
Internal Audit: Massa-Signature

### ISSUE THREAD

**Issue by dr-chain** [massalabs/massa#3816]
The following are some proposed improvements in [Massa-Signature](https://github.com/massalabs/massa/tree/main/massa-signature).

- [x] The code does batch signature verification when the total number of signatures to verify is more than 1. However, w.r.t. performance, it was observed that it is faster to individually verify signatures below a certain number (say <10), so the condition can be changed to that number instead of the current value (1) and the code should be edited to add a loop for the same. Above this value, batch signature verification can be done as usual.
- [ ] The `debug()` and `display()` functions can be combined to reduce code redundancy.
- [x] Merge `to_bytes()` and `into_bytes()` for public key, signature to reduce redundancy.
- [ ] Merge common functions for key pair, public key, and signature to reduce redundancy. e.g. `debug()/display()`, `serialize()`, `deserialize()`, etc.

**Comment by damip** [comment]
My 2 cents:
* batch verif
  * benchmarks are here: https://github.com/massalabs/massa/issues/3071#issuecomment-1263475067
  * benchmarks say that batching becomes relevant for N > 1 but is less efficient for N = 1, that's why we programmed it this way, but we could add a loop for more genericity if we decide to change the threshold in the future
* signature buffer length:
  * the current version checks that the buffer still has enough bytes to deserialize a signature from
  * changing the condition to `buffer.len() == SIGNATURE_SIZE_BYTES` would make the function fail if the remaining buffer is exactly the signature size
  * so the current implementation is OK

**Comment by dr-chain** [comment]
@damip Thanks for the explanation. I thought the threshold was some number above 1. If it is one, maybe the current code can be retained.

For this - `changing the condition to buffer.len() == SIGNATURE_SIZE_BYTES would make the function fail if the remaining buffer is exactly the signature size`, I made a mistake. I have edited the original post to make it `!=`.

**Comment by damip** [comment]
> For this - `changing the condition to buffer.len() == SIGNATURE_SIZE_BYTES would make the function fail if the remaining buffer is exactly the signature size`, I made a mistake. I have edited the original post to make it `!=`.

The buffer might contain more followup bytes but we only want to read what we need. So the current implem is ok

**Comment by dr-chain** [comment]
@damip ok. I have edited the post.

**Comment by Eitu33** [comment]
IMHO this issue can be closed for the following reasons:

> "It was observed that it is faster to individually verify signatures below a certain number (say <10), so the condition can be changed to that number instead of the current value (1) and the code should be edited to add a loop for the same"

This has been resolved by https://github.com/massalabs/massa/issues/3816#issuecomment-1520798174.

> "The debug() and display() functions can be combined to reduce code redundancy."

In an ideal world they would, but currently we use both traits in the entire code base and an object like `KeyPair` has numerous implications in others objects, which also have other implications etc., and it makes this change much more important than what it looks like. Also this is very far from being a serious case of redundancy, and does not undermine the understanding of the module.

> "Merge to_bytes() and into_bytes() for public key, signature to reduce redundancy."

Already done.

> Merge common functions for key pair, public key, and signature to reduce redundancy. e.g. debug()/display(), serialize(), deserialize(), etc.

Two things here: some code might seem similar at the module level, but we cannot talk about redundancy here as these functions have different behaviours and different applications in other modules. For PublicKey specifically I agree that there is redundancy, which brings me to my second point. Even is there was, this is not applicable because of the amount of changes it would require project-wise for something that is fairly unimportant.

**Comment by Eitu33** [comment]
I'm closing this, feel free to re-open it if you disagree with my decision
