### ISSUE TITLE
Enable transaction creator to pay for storage

### ISSUE THREAD

**Issue by plouis01** [massalabs/massa#3996]
When a contract is storing some data on-chain, the contract has to pay for gas storage and not the transaction creator. This can resolve high costs for the contract creator and even spam to make the contract unusable (by using all the Massa in it).

It would be possible to make the transaction creator pay for storage directly at the protocol level to prevent this. 
As this feature won't be needed by everybody, it can be an option that the contract creator chooses when initializing it.

The other way to make the transaction creator pay is to check if enough Massa has been sent before but this would require another transaction and thus won't be suitable for front-end usage.

**Comment by AurelienFT** [comment]
@damip If you have some time it could be interesting to have your input on that.

**Comment by damip** [comment]
You can make sure that :

* get the current balance of the SC and store it as the "initial_coins" variable
* perform all the tasks of the SC
* get the current balance of the SC and store it as the "final_coins" variable
* assert that the `coins` of the transaction is strictly higher than `initial_coins - final coins`, otherwise generate an error to revert the execution
* optionally send back any excess payment `(coins - (initial_coins - final_coins))` to the caller

**Comment by plouis01** [comment]
Ok, thanks, we can do it this way. Plus, I don't see how we can implement it any other way other than at the protocol level.
