### ISSUE TITLE
High RAM usage

### ISSUE THREAD

**Issue by damip** [massalabs/massa#4129]
## Settings

* heaptrack on testnet 23.2 compiled in debug
* 2ktxps load
* no API activity
* no staking
* only 11 outgoing connections

## Default version

![image](https://github.com/massalabs/massa/assets/10211103/c0395339-3952-4761-b647-1afb78afcfa3)

**Peak usage: 3.4GB**  

Largest peak consumers:
* protocol operation retrieval thread (2.3GB, 68%)
  * note_operaitions_from_peer  (1.6GB, 46.8%)
    * storage store_operations (1.4GB, 41.9%)
      * OperationIndexes
  * on_operations_announcements_received (650MB, 19%)
    * LRU
* blcok retrieval thread (533MB, 15%)
  * on_block_full_operations_received (460MB, 13%)
    * storage store_block (274MB, 8%)
      * block_indexes

## Default version modified by adding shrink_to_fit on operation Storage containers

![image](https://github.com/massalabs/massa/assets/10211103/8f781624-6605-45d6-b4a9-a1898b1d31c6)

(drop at the end is on CTRL+C and takes time because of https://github.com/massalabs/massa/issues/4121 )

**peak usage = 2.8GB**

Largest peak consumers:
* protocol operation retrieval thread (2GB, 71%)
  * note_operations_from_peer (1.1GB, 37.3%)
    * Storage => store operations => storage::operationIndex (694MB, 24%)
    * insert_checked_operation (293MB, 10.3%)
      * LRU
  * on_operations_announcements_received (941MB, 33.1%)
    * LRU
* block retrieval thread (474MB, 16.7%)
  * on_block_full_operations_received (439.9MB, 15.5%)
    * Storage::sotre_block=>BlockIndexes (305MB, 10.7%)

**Comment by damip** [comment]
TODO:
* investigate why `note_operations_from_peer` makes operation Storage peak so high
* reduce LRU size on `on_operations_announcements_received`
* investigate why `on_block_full_operations_received` makes block Storage peak so high

**Comment by damip** [comment]
Possible explanations for the storage peaks:
* hashmap overhead: https://ntietz.com/blog/rust-hashmap-overhead/  => maybe reallocate by ourselves more finely than doubling capacity ? find another container ?
* operations sent to operation pool accumulate infinitely until the op pool robot activates (every 5seconds). Maybe cap the amount of ops waiting for the robot ?

**Comment by AurelienFT** [comment]
For the caches used in on_operations_announcements_received we have : 

- `ops_known_by_peer`: LruMap<PeerId, LruMap<OperationPrefixId, ()>>: First LRU is limited to max_in connections + max_out_connections. Nested LRU is limited by `max_node_known_ops_size` set to 200000
- `asked_operations`: LruMap<OperationPrefixId, (Instant, Vec<PeerId, Global>)> Limit set to `max_known_ops_size` which is 2 millions. As this LRU contains a vec as value maybe 2 millions is too much

In the block retrieval we save block for some time directly in his storage. With the current config of the consensus we save the same number of blocks here and in consensus (approx 1000) and so that's why we don't see memory from the consensus there it's because it's the same blocks already saved by protocol. We should see it if we increase `force_keep_final_periods_without_ops` back to 128.
But 500MB is still big for 1000 blocks that should be only header + list of opid + serialized version so #4108 is still relevant

**Comment by damip** [comment]
Thank you @AurelienFT . Made some improvements: https://github.com/massalabs/massa/pull/4134
