### ISSUE TITLE
invalid gasLimit

### ISSUE THREAD

**Issue by peterjah** [massalabs/massa#4392]
**Context**
When using "send_operations" endpoint with a big value for maxgas, the operation is submitted successfully, operation ID is returned but the transaction is not processed.

What are the constraints behind this?

**Describe the solution you'd like**
If the maxGas value is invalid, it would be nice to return an error.
If its more complicated than that,  another way would be to emit en error event which could be retrieved when listening smart contract events in context of SC deployment or SC call.

I know it is already possible to check the operation status of an operation using OperationInfo but returning directy will make a smoother developer experience!

**Comment by qdrn** [comment]
I believe it's part of a more general improvement of the `send_operations` endpoint. There is the same problem if you send an operation with an "invalid" `expire_period`. It will fail silently. I think in those case we should return meaningful error messages to help people. Otherwise it can take a while to understand what's wrong.
