### ISSUE TITLE
Test Buildnet Explorer

### ISSUE THREAD

**Issue by longgamma-massa** [massalabs/massa#4445]
**Context:**
We'd appreciate 2 people to test Buildnet Explorer at https://explorer.massa.net/. 

**Describe the solution you'd like**
Gather feedback, issues, and suggestions if you have in a Document. 
Please provide screenshots, console logs (if any errors), and other details so that it's easy to find the issue.

**Additional context**
Product is in active development, hence you might have moments when the website is not responsive.

**Comment by aoudiamoncef** [comment]
Congratulations @longgamma-massa

I really enjoyed the general design and I'm sure that It'll be far better with the latest release of Massa APIs

There some personal subjective feedback about the explorer:

- We have no data here 
![image](https://github.com/massalabs/massa/assets/22281426/505affd2-0137-4dcf-b9f4-77a955010e7f)

- We can add more details in info bubbles
![image](https://github.com/massalabs/massa/assets/22281426/0ad34512-ed9f-4841-b1b6-0cfa3210f44a)

- May be we could find a better icon for operations
![image](https://github.com/massalabs/massa/assets/22281426/db440acc-dffd-4ba2-8f23-f47833e8e4b2)

- Having a simple filter for candidate/filter in the UI could be a game changer
![image](https://github.com/massalabs/massa/assets/22281426/60dc8a1c-e1fb-4ba2-a80e-5a48d8ed4251)

- The info message could be more verbose and placed lower between the title and the table
![image](https://github.com/massalabs/massa/assets/22281426/0f7afe5b-d16b-4f6d-9197-427180ae3fac)

- We could have more contrast by adding red color
![image](https://github.com/massalabs/massa/assets/22281426/8c97516a-f8d5-4a62-b6ea-e564a1e51494)

- It's not the same icon as the home page
![image](https://github.com/massalabs/massa/assets/22281426/d524a1d4-a685-499c-a51f-00d2bcb2bdbf)

- Make the placeholder grey and why not add CTRL+K shortcut
![image](https://github.com/massalabs/massa/assets/22281426/ca7a78af-833d-4d3e-a1ad-3ce74803f4b8)

- Why we are using blue instead of red ?
![image](https://github.com/massalabs/massa/assets/22281426/0c963e10-9ddf-42ec-a06f-96e2cfc059a6)

- This little bit too much text
![image](https://github.com/massalabs/massa/assets/22281426/30e3bee1-85dd-457b-9987-b59e470d756a)

- What is the signification of this red icon ?
![image](https://github.com/massalabs/massa/assets/22281426/2475fa9e-3c38-40ab-b204-0f7a0b8c9d10)
![image](https://github.com/massalabs/massa/assets/22281426/577cb473-6fc3-43c5-aae8-d3e92db312e3)

**Comment by longgamma-massa** [comment]
Thanks @aoudiamoncef, really appreciate! If you have an idea how to investigate what other info can be added to the 'info bubbles' (or have ideas yourself) please share freely. This is valuable info to us :)
