### ISSUE TITLE
Read_only gas_used value cannot be used to estimate the gas needed when the contract called init new calls

### ISSUE THREAD

**Issue by Leo-Besancon** [massalabs/massa#4573]
When we return the gas cost of a read_only_execution, we check against the max_instance_cost in order to make it easier to have a ggas estimation.
 
```rust
let exact_cost = req.max_gas.saturating_sub(exec_response.remaining_gas);
Ok(ReadOnlyExecutionOutput {
  out: execution_output,
  // return max_instance_cost if the exact cost is below
  // users can paste the estimated amount into a real call
  // without having to worry about underlying limits
  gas_cost: if exact_cost > self.config.gas_costs.max_instance_cost {
    exact_cost
  } else {
    self.config.gas_costs.max_instance_cost
}
```

The problem is that this check is only made at the base level call_sc, but not for abi calls inside.
We need to return a mix of gas_used, which may not be easily done.

Example: We make a call with max_gas of 2_400_000.
> Call_0_0 (real init cost: 100_000) - Available gas after: 2_300_000
	> Call_1_0 (real init cost: 100_000) - Available gas after: 2_200_000
	> Call_1_1 (real init cost: 100_000) - Available gas after: 2_100_000
	> Call_1_2 (real init cost: 100_000) - Available gas after: 2_000_000
	> Call_1_3 (real init cost: 100_000) - Fails because <= 2_100_000.

Here, we will return a gas_used of 2_100_000, but a real call if 2_100_000 will fail immediately.
We should return a gas estimation of 2_500_000 to ensure everything passes.

Tasks:
- [x] #4586
- [ ] Fix computation of `max_gas` see: https://github.com/massalabs/massa/issues/4573#issuecomment-1833595505

**Comment by damip** [comment]
## Simplification idea

### Explanation

Always debit `max_instance_cost` at every call to simplify things.

### Issue

It's a high number, it will cause a lot of gas waste so let's not do it.

## Read-only estimate fix idea

### Explanation

In the execution context, we save the used gas since the beginning of the top-level execution just before the latest sub-execution (can be at any stack depth, can also be None if there are no sub-executions) in a `ctx.gas_used_until_last_subexecution: Option<u64>`. The assumption is that the remaining gas at that point needs to be at least `max_instance_cost`.

Then at the end of  the read-only call [here](https://github.com/massalabs/massa/blob/6499d2ee62e667dbf601e0e3416cce91a0dfabcd/massa-execution-worker/src/execution.rs#L1517-L1521):

```rust
gas_cost: max(
    exact_cost,
    ctx.gas_used_until_last_subexecution.unwrap_or_default().saturating_add(max_instance_cost)
);
```

WARNING: make sure you init `ctx.gas_used_until_last_subexecution` to `None` in `ExecutionContext::new` and add it to snapshots as well to keep its value consistent

**Comment by bilboquet** [comment]
- [ ] Add some context to `Provided gas 1895238 is lower than the base instance creation gas cost 2100000.`

Complementary to the issue above:

Here is a test case with a poor / misleading error message: 
- Readonly call correctly provides a max gas value of 3728755.
- When this max gas is used in the send_operation, an error occurs: `Provided gas 1895238 is lower than the base instance creation gas cost 2100000.`

This seems to be a nested call issue:
the schema is something like:
- an operation calls a SC1 with 3728755 gas
- SC1 use some gas 
- SC1 calls SC2 with 1895238
- SC2 fails with `Provided gas 1895238 is lower than the base instance creation gas cost 2100000`
