### ISSUE TITLE
staking

### ISSUE THREAD

**Issue by sekomer** [massalabs/massa#4640]
hi,

I couldn't find any information about delegation, in order to stake tokens, do I need to run a validator node? or can I delegate on some other validators and earn rewards

thanks!

**Comment by damip** [comment]
There is no L1 delegation in Massa, but it is easy to run a node on a normal desktop computer and stake from there! See https://docs.massa.net/docs/node/install 

Otherwise,  please wait for the upcoming DeFi liquidity incentives program (see https://ca.finance.yahoo.com/news/revolutionary-massa-ecosystem-launching-now-214500279.html )
